### ISSUE TITLE
initial issues

### ISSUE THREAD

**Issue by oliverfoster** [cgkineo/adapt-launchNewWindow#1]
* in progress status text
* window.open string
    * specify options
* don't initialize / do initialize scorm control

**Comment by moloko** [comment]
> don't initialize / do initialize scorm control

Don't worry too much about this yet, I'm more interested in knowing what happens as things stand. Make the other changes then we'll give it a test and see what's what.

**Comment by oliverfoster** [comment]
:+1:

**Comment by oliverfoster** [comment]
sorted @moloko 

i'm not keen on the configModel override, but that's life.

**Comment by oliverfoster** [comment]
i think this should be ready to test? it's got the default text in from the one you sent me, plus the default behaviour from it also.

**Comment by moloko** [comment]
First issue I've found is that it ALWAYS activates, no matter which page you launch from. 

So, if you launch the course from index.html the extension kicks in and redirects you to index_lms.html

99% of the time you'd only want this extension to run if launching the course via index_lms.html BUT to cope for the other 1% it would be useful to be able to specify a list of pages that trigger activation

**Comment by moloko** [comment]
Also, there's no need for it to do anything when 'current window' is the required setting. It should just let Adapt run as normal.

**Comment by moloko** [comment]
I think the vast majority of use-cases for this will be 'When run from the LMS I want the course to launch in a new window if the user is running the course on iOS'

**Comment by moloko** [comment]
Another possible use-case: client is launching the course in two different environments:
1. from a web server, where the course is embedded in the page via an iframe
1. from an LMS where the course is displayed in a new window with no iframe/frameset

In that example, I'd want to configure this extension to launch in a new window only when index.html is run on iOS

**Comment by oliverfoster** [comment]
cool

**Comment by oliverfoster** [comment]
we can do all of this now right? @moloko

**Comment by moloko** [comment]
yep I think you're right
