### ISSUE TITLE
Safari on IPAD 13.5.1

### ISSUE THREAD

**Issue by lorenzton** [cgkineo/adapt-launchNewWindow#10]
On ipad 13.5.1 
Using in active on html selector ".os-ios" -> no new window in safari (in chrome works)
Using in active on html selector "*" -> new window in safari and in chrome.

**Comment by oliverfoster** [comment]
what about `.ipad` ?

**Comment by lorenzton** [comment]
active on html selector  = .os-ios, .os-android, .ipad, .os-ipad, .os-ipados

no new window in safari (in chrome works)

**Comment by oliverfoster** [comment]
Can you try this > https://forums.developer.apple.com/thread/119186#thread-post-373517

It looks like it might be being recognised as macosx rather than ios

**Comment by lorenzton** [comment]
Yes, now it works. It's that setting. Thank you.
