### ISSUE TITLE
v3 compatibility

### ISSUE THREAD

**Issue by danielghost** [cgkineo/adapt-launchNewWindow#5]
The following updates mean the SCORM tracking never gets initialized:
https://github.com/adaptlearning/adapt_framework/commit/48636843c107ae1cf5de0a9a497b96e44ac757f4#diff-6b5c70782274918f15c760a1f8b4ec6e

https://github.com/adaptlearning/adapt-contrib-spoor/commit/79be906ad88c6b4a8952c3210d92466c0ba0aa66

**Comment by moloko** [comment]
Really wish I'd looked at the issues for this extension earlier than I did, would have saved me a lot of head-scratching!

**Comment by moloko** [comment]
should be fixed 65487867b5102659ad9e8481e28b8725e474815a
