### ISSUE TITLE
SCORM  tracking

### ISSUE THREAD

**Issue by lorenzton** [cgkineo/adapt-launchNewWindow#9]
v0.1.1 - SCORM tracking doesn't work; I'm using AT . 

Thank you

**Comment by olivermartinfoster** [comment]
Could you be more specific? Neither this launchNewWindow extension nor the AAT are responsible for or provide SCORM tracking functionality. That job is taken by the spoor extension and an LMS.

**Comment by lorenzton** [comment]
I finished the tests now; it seems that Moodle + New window plugin + Chrome on Windows = SCORM tracking doesn't work. Also Chrome on Mac has some problems, if the window isn't full screen. In other OS it works.

Thank you

**Comment by oliverfoster** [comment]
what is your launchNewWindow configuration? what are some of the problems you're experiencing on mac osx? what do you mean by "SCORM tracking doesn't work"? Is it not completing on the lms? or is it not restoring completion in the course? or is it not restoring question answers?

**Comment by lorenzton** [comment]
"_launchNewWindow": {
    "_isEnabled": true,
    "_stopSessionInitialize": true,
    "_activeOnPages": [
      "index_lms.html"
    ],
    "_activeOnSelector": "*",
    "_target": "courseWin",
    "_strWindowFeatures": "width={{width}},height={{height}},menubar=no,location=no,directories=no,resizable=yes,scrollbars=yes",
    "_delay": "2000",
    "preLaunchTitle": "The course should now open in a new browser window.",
    "preLaunchBody": "If this does not occur, please deactivate any popup blocking software - then <a href=\"{{href}}\" target=\"_blank\">click here</a> or refresh this page to try again.",
    "launchTitle": "Launched",
    "launchBody": "Please ensure you don't close or do anything in this window whilst the course is in progress.",
    "closedTitle": "You have closed the course.",
    "closedBody": "Please close this window to continue."
  }

**Comment by lorenzton** [comment]
_what are some of the problems you're experiencing on mac osx?_
chrome on mac osx; if the chrome window isn't full screen, the system doesn't track anything. 

_what do you mean by "SCORM tracking doesn't work"? Is it not completing on the lms? or is it not restoring completion in the course? or is it not restoring question answers?_
I answer the questions in the course, but the LMS doesn't save the data. Restoring question answers works.

**Comment by oliverfoster** [comment]
![image](https://user-images.githubusercontent.com/7974663/84046745-67d48b00-a9a2-11ea-8e49-d2b032f672ae.png)
As you can see it is completing on the LMS for me, it is saving the completion states and it is restoring questions. I have the same config.

>  ...but the LMS doesn't save the data. Restoring question answers works.

If it is restoring question answers then it must be saving data to the LMS. Is the LMS not marking the course as completed?

> ...if the chrome window isn't full screen, the system doesn't track anything

No restored question answers? Do you have any console logs?

**Comment by lorenzton** [comment]
Chrome on Windows
If I complete the course (all pages, all questions)  data is saved and questions are restored when I open it. 
If I don't complete the course, when I re-open it, I restart it (no data saved). 

In other browsers (i.e. Firefox on windows) - if I answer some questions, then I close the course, when I re-open it, I continue from the last question, and previous answers are saved.

**Comment by lorenzton** [comment]
Chrome on Mac OSX
If _strWindowFeatures: "width=500,height=500,menubar=no,location=no,directories=no,resizable=yes,scrollbars=yes",
If I complete the course (all pages, all questions) data is saved and questions are restored when I open it.
If I don't complete the course, when I re-open it, I restart it (no data saved).

PS
I'm using 500/500 and not standard values because in windows + chrome, the course window is bigger than the screen and the button "Continue" is not visible. Users have to maximize the window so the button appear on the right position. Many times new users can't find the button so they send help emails.

**Comment by olivermartinfoster** [comment]
Can I have some screenshots of the console output on Mac ?

**Comment by lorenzton** [comment]
Here you can find the log Mac and Win. 
Thank you
[win.log](https://github.com/cgkineo/adapt-launchNewWindow/files/4751547/win.log)
[macosx.log](https://github.com/cgkineo/adapt-launchNewWindow/files/4751548/macosx.log)

**Comment by oliverfoster** [comment]
I think you're running into an LMS bug. It sounds like the SCORM data isn't being saved after the window is closed and when the course isn't complete. 

Chrome recently broke the LMS side of the SCORM API in some LMSes. The window is closed so the javascript context gets destroyed before the SCORM API can save the data to the LMS. 

https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/js/adapt-contrib-spoor.js#L140 this line fails.

The reason it works when you complete the course is because the SCORM data is commited to the LMS on course status changes, which you can see referenced here https://github.com/adaptlearning/adapt-contrib-spoor/blob/master/js/adapt-contrib-spoor.js#L67

You'll probably need something like this https://github.com/adaptlearning/adapt-contrib-spoor/pull/195 so that spoor commits the data to the lms any time it changes rather than waiting until the window is closed or the course status changes.

**Comment by oliverfoster** [comment]
I'm going to close this issue as it isn't related to adapt-launchNewWindow
